version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-retro_exchange}
      POSTGRES_USER: ${DB_USER:-retro_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-retro_pass}
    ports:
      - "5432:5432"
    volumes:
      - retro_db:/var/lib/postgresql/data
    networks:
      - retro_net

  api1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_INIT: "1"  
      INSTANCE_ID: "api1"
      DATABASE_URL: "postgresql+psycopg2://${DB_USER:-retro_user}:${DB_PASSWORD:-retro_pass}@db:${DB_PORT:-5432}/${DB_NAME:-retro_exchange}"
      SECRET_KEY: ${SECRET_KEY:-dev-only-change-me-please-very-long-string}
    depends_on:
      - db
    networks:
      - retro_net

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_INIT: "0" 
      INSTANCE_ID: "api2"
      DATABASE_URL: "postgresql+psycopg2://${DB_USER:-retro_user}:${DB_PASSWORD:-retro_pass}@db:${DB_PORT:-5432}/${DB_NAME:-retro_exchange}"
      SECRET_KEY: ${SECRET_KEY:-dev-only-change-me-please-very-long-string}
    depends_on:
      - db
    networks:
      - retro_net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api1
      - api2
    networks:
      - retro_net

volumes:
  retro_db:

networks:
  retro_net:
    driver: bridge
